---
# This workflow will install Python dependencies and run tests

name: Unit-Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with Django unit tests
        env:
          # For unit tests, secret_key just needs to be populated.
          # It will only ever access a temporary Django test database.
          SECRET_KEY: unit-test-fake-secret-key-#5TY90
        run: |
          python manage.py test --debug-mode
